version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  template-init-flow-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    template-init-flow-test:
      jobs:
        - template-init-flow-test
